name: Metal News
favicon: null
layout_spectrum: 0.6890271303709596
typography_spectrum: 0.19662864413112402
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3339165123179555
  lightness: 0.4168001040816307
  saturation: 0.8844990830402821
  rhythmicContrast: 0.4867900060489774
purpose: []
